### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by biobenkj** [mandel01/pyinseq#10]
It would be ideal to have a user tutorial/development documentation setup so that we can quickly sort out who is working on what, progress, etc. Github also renders IPython notebooks now, so we could use that. Otherwise I suggest using readthedocs.org. 

I like how the khmer project is set up. 

See: http://khmer.readthedocs.org/en/v1.4.1/

Thoughts?

**Comment by mandel01** [comment]
Documentation on Github is now improved with the functional pipeline. Will work on this long-term.
