### ISSUE TITLE
Improve appearance of documentation

### ISSUE THREAD

**Issue by mandel01** [mandel01/pyinseq#20]
e.g. File formats (gbk and how it can have multiple contigs; ftt format).

**Comment by titipata** [comment]
We can start `gh-pages` branch for documentation and move markdown documentation there. This will be rendered at `mandel01.github.io/pyinseq`. There are few Jekyll documentation themes that we can select such as [jekyll-docs-template](https://github.com/bruth/jekyll-docs-template).

**Comment by titipata** [comment]
@mandel01, I put documentation in `gh-pages` branch [here](https://github.com/titipata/pyinseq/tree/gh-pages). This is for now serve at http://titipata.github.io/pyinseq/. You can take a look and feel free to let me know if it's good or not.

**Comment by mandel01** [comment]
I'm going to change the name of this issue to deal with the appearance of the documentation and then move items about the content of the documentation to a different issue -  #35.

**Comment by mandel01** [comment]
I like the idea of having a clean landing page for the project, with documentation that is autogenerated. I looked at the linked templates but I first need to read more about using jekyll and github pages. Is all of the text on the page autogenerated from the `docs/` directory or is some of it static in the html?

**Comment by titipata** [comment]
I think there is a way to do that as I searched through: https://gist.github.com/cobyism/4730490. In Jekyll case, we can sync `/docs` folder with Jekyll `_posts` folder.

**Comment by mandel01** [comment]
Hi @titipata. It has taken me a long time to get to some of these issues. I learned how to use sphinx and applied that for the documentation. It does not auto-update but that will be for a future update.
