### ISSUE TITLE
Github displays wrong language

### ISSUE THREAD

**Issue by mandel01** [mandel01/pyinseq#22]
Github lists `pyinseq` as an HTML project (in searches and in the "bar" at the top of the main page) due to the documentation in the packaged `bowtie` files. According to [this link](https://github.com/github/linguist/blob/master/README.md) we should "consider moving the files into one of the [paths for vendored code](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml), or [use the manual overrides](https://github.com/github/linguist/blob/master/README.md#overrides) feature to ignore them."

How about changing the packages/ directory to be named /dependencies ? Is that enough?

Would also need to tell bowtie where to find itself in `config.py`.

**Comment by mandel01** [comment]
Would also need to tell `bowtie` where to find itself in `config.py`

**Comment by mandel01** [comment]
@rebeldroid12 would you be interested in tackling this? (since you did a nice job putting in the bowtie packages... but also because I've been painfully slow to send the other notes!)

**Comment by rebeldroid12** [comment]
@mandel01 got it! assign it to me :+1:

**Comment by mandel01** [comment]
Awesome, thanks!
